url: https://adaptiv.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Adaptiv
email: hej@adaptiv.se
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Adam Killander
  pic: 1
  about: Systemutvecklare, teamledare, förbättringscoach, teaterapa.

- name: Johan Dewe
  pic: 2
  about: Utvecklare och arkitekt som har kodat system, oftast bakom webben, sedan mitten av nittiotalet.

- name: Joakim Manding Holm
  pic: 3
  about: Erfaren konsult som främst bistår med agil coachning, ledarskap och förändring.

- name: Johan Hallstensson
  pic: 4
  about: Erfaren och kunnig utvecklare som noga följer med i den tekniska frontlinjen.

- name: Måns Sandström
  pic: 5
  about: Agil utveckling, allt ifrån det tekniska, till ledarskap, organisation och förändringsledning.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/adaptivsthlm
  - title: linkedin
    url: https://se.linkedin.com/company/adaptiv-sthlm-ab

# Build settings
markdown: kramdown
permalink: pretty
