url: https://adaptiv.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Adaptiv
description: "Adaptiv är ett IT-konsultbolag med verksamhet i Stockholmsområdet. Vår utgångspunkt är att de produkter, system och funktioner vi skapar ska ge verklig affärsnytta och nöjda kunder. Vi kan skapa de metodmässiga och tekniska förutsättningarna för detta."

# Team names, titles and social links
team-org-people:
- name: Adam Killander
  pic: 1
  about: Systemutvecklare (fokus på Javascript, Java), teamledare/coach, agil coach, harmoniskapande teaterapa
  social:
  - title: twitter
    url: http://twitter.com/adamkillander
  - title: linkedin
    url: https://www.linkedin.com/in/adamkillander/

- name: Joakim M. Holm
  pic: 3
  about: Organisationsutvecklare, interimschef, teamledare/coach, systemutvecklare (fokus på Elixir, Java), pianistisk idealist
  social:
  - title: twitter
    url: http://twitter.com/jockeholm
  - title: linkedin
    url: https://www.linkedin.com/in/jockeholm/

- name: Måns Sandström
  pic: 5
  about: Systemutvecklare (fokus på Ruby, Elixir, Java), ledarskapscoach, organisationsutvecklare, förändringsguide
  social:
  - title: twitter
    url: http://twitter.com/manssandstrom
  - title: linkedin
    url: https://www.linkedin.com/in/manssandstrom/

team-tech-people:
- name: Adam Killander
  pic: 1
  about: Systemutvecklare (fokus på Javascript, Java), teamledare/coach, agil coach, harmoniskapande teaterapa
  social:
  - title: twitter
    url: http://twitter.com/adamkillander
  - title: linkedin
    url: https://www.linkedin.com/in/adamkillander/

- name: Johan Dewe
  pic: 2
  about: Systemutvecklare (fokus på Go, Javascript, .Net), teknisk ledare/coach, teamledare/coach, snöälskande docent
  social:
  - title: twitter
    url: http://twitter.com/johandewe
  - title: linkedin
    url: https://www.linkedin.com/in/johandewe/

- name: Johan Hallstensson
  pic: 4
  about: Systemutvecklare (fokus på Elixir, Ruby), teknisk ledare/coach, mobbprogrammeringsexpert, teamkär egenfixare
  social:
  - title: twitter
    url: http://twitter.com/jlind

- name: Måns Sandström
  pic: 5
  about: Systemutvecklare (fokus på Ruby, Elixir, Java), ledarskapscoach, organisationsutvecklare, förändringsguide
  social:
  - title: twitter
    url: http://twitter.com/manssandstrom
  - title: linkedin
    url: https://www.linkedin.com/in/manssandstrom/

    # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/adaptivsthlm
  - title: linkedin
    url: https://se.linkedin.com/company/adaptiv-sthlm-ab

# Build settings
markdown: kramdown
permalink: pretty
