url: https://adaptiv.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Adaptiv
description: "Adaptiv är ett IT-konsultbolag med verksamhet i Stockholmsområdet. Vår utgångspunkt är att de produkter, system och funktioner vi skapar ska ge verklig affärsnytta och nöjda kunder. Vi kan skapa de metodmässiga och tekniska förutsättningarna för detta."

# Team names, titles and social links
people:
- name: Adam Killander
  pic: 1
  about: Systemutvecklare (fokus: Javascript, Java), teamledare/coach, agil coach, teaterapa

- name: Johan Dewe
  pic: 2
  about: Systemutvecklare (fokus: Go, Javascript, .Net), teknisk ledare/coach, teamledare/coach, agil arkitekt, lektor

- name: Joakim Manding Holm
  pic: 3
  about: Organisationsutvecklare, förändringsguide, teamledare/coach, systemutvecklare (fokus: Elixir, Java), världsförbättrare

- name: Johan Hallstensson
  pic: 4
  about: Systemutvecklare (fokus: Elixir, Ruby), teamkär ensamvarg

- name: Måns Sandström
  pic: 5
  about: Systemutvecklare (fokus: Ruby, Elixir, Java), ledarskapscoach, organisationsutvecklare, förändringsguide, utanför ramen-tänkande filosof

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/adaptivsthlm
  - title: linkedin
    url: https://se.linkedin.com/company/adaptiv-sthlm-ab

# Build settings
markdown: kramdown
permalink: pretty
